[package]
name = "seven_segment_display"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-where = "1.2.5"
ferrum_hdl = { path = "../ferrum_hdl/" }
